#!/bin/env zsh
setopt EXTENDED_GLOB
for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do
    ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
done
if [ -f "${ZDOTDIR:-$HOME}/.zshrc" ]; then
    echo "export TERM=vt102" >> "${ZDOTDIR:-$HOME}/.zshrc"
fi